import 'package:loom_run/features/crm/models/follow_up.dart';
import 'package:loom_run/features/crm/models/lead.dart';

/// Seed data used by CRM widget tests (controllers no longer seed in production).
List<Lead> testSeedLeads() {
  final now = DateTime.now();
  DateTime ago(Duration d) => now.subtract(d);
  return [
    Lead(
      id: 'lead-1',
      name: 'Raghu',
      company: 'Exora Solutions',
      phone: '+91 98450 11223',
      location: 'Bangalore',
      source: LeadSource.whatsapp,
      score: 50,
      status: 'Busy',
      stage: LeadStage.newLead,
      value: 10000,
      lastActivity: ago(const Duration(minutes: 50)),
    ),
    Lead(
      id: 'lead-2',
      name: 'Sunita Desai',
      company: 'Arvind Mills',
      phone: '+91 99201 44556',
      location: 'Ahmedabad',
      source: LeadSource.referral,
      score: 82,
      status: 'Interested',
      stage: LeadStage.contacted,
      value: 620000,
      lastActivity: ago(const Duration(hours: 5)),
    ),
    Lead(
      id: 'lead-3',
      name: 'Nikhil Rao',
      company: 'Welspun India',
      phone: '+91 98330 22114',
      location: 'Mumbai',
      source: LeadSource.website,
      score: 34,
      status: 'Callback',
      stage: LeadStage.contacted,
      value: 85000,
      lastActivity: ago(const Duration(hours: 26)),
    ),
    Lead(
      id: 'lead-4',
      name: 'Priya Nair',
      company: 'Vardhman Textiles',
      phone: '+91 90080 91234',
      location: 'Ludhiana',
      source: LeadSource.whatsapp,
      score: 76,
      status: 'Requirement shared',
      stage: LeadStage.requirementCollected,
      value: 320000,
      lastActivity: ago(const Duration(hours: 3)),
    ),
    Lead(
      id: 'lead-5',
      name: 'Lakshmi Iyer',
      company: 'KPR Mill',
      phone: '+91 97890 55321',
      location: 'Coimbatore',
      source: LeadSource.phoneCall,
      score: 68,
      status: 'Quote sent',
      stage: LeadStage.quoted,
      value: 780000,
      lastActivity: ago(const Duration(days: 2)),
    ),
    Lead(
      id: 'lead-6',
      name: 'Ashok Menon',
      company: 'Raymond Ltd',
      phone: '+91 98110 77654',
      location: 'Thane',
      source: LeadSource.referral,
      score: 88,
      status: 'Negotiating',
      stage: LeadStage.negotiation,
      value: 1450000,
      lastActivity: ago(const Duration(days: 1)),
    ),
    Lead(
      id: 'lead-7',
      name: 'Farah Khan',
      company: 'Bombay Dyeing',
      phone: '+91 99870 33221',
      location: 'Mumbai',
      source: LeadSource.instagram,
      score: 91,
      status: 'Won',
      stage: LeadStage.won,
      value: 1900000,
      lastActivity: ago(const Duration(days: 4)),
    ),
    Lead(
      id: 'lead-8',
      name: 'Deepak Joshi',
      company: 'RSWM Ltd',
      phone: '+91 94140 88123',
      location: 'Bhilwara',
      source: LeadSource.website,
      score: 22,
      status: 'Not interested',
      stage: LeadStage.lost,
      value: 150000,
      lastActivity: ago(const Duration(days: 8)),
    ),
  ];
}

List<FollowUp> testSeedFollowUps() {
  final now = DateTime.now();
  DateTime at(int dayOffset, int hour, int minute) => DateTime(
        now.year,
        now.month,
        now.day + dayOffset,
        hour,
        minute,
      );
  return [
    FollowUp(
      id: 'fu-1',
      leadId: 'lead-3',
      customerName: 'Nikhil Rao',
      company: 'Welspun India',
      phone: '+91 98330 22114',
      dateTime: at(-1, 11, 0),
      action: 'Follow up on quotation response',
      relatedRef: 'QT-418',
      highPriority: true,
    ),
    FollowUp(
      id: 'fu-2',
      leadId: 'lead-8',
      customerName: 'Deepak Joshi',
      company: 'RSWM Ltd',
      phone: '+91 94140 88123',
      dateTime: at(-3, 15, 0),
      action: 'Re-engage after no reply for two weeks',
    ),
    FollowUp(
      id: 'fu-3',
      leadId: 'lead-2',
      customerName: 'Sunita Desai',
      company: 'Arvind Mills',
      phone: '+91 99201 44556',
      dateTime: at(0, 10, 30),
      action: 'Confirm greige fabric specifications',
      relatedRef: 'QT-419',
      highPriority: true,
      outcome: FollowUpOutcome.quote,
    ),
    FollowUp(
      id: 'fu-4',
      leadId: 'lead-1',
      customerName: 'Raghu',
      company: 'Exora Solutions',
      phone: '+91 98450 11223',
      dateTime: at(0, 14, 0),
      action: 'Share revised pricing and catalogue',
    ),
    FollowUp(
      id: 'fu-5',
      leadId: 'lead-4',
      customerName: 'Priya Nair',
      company: 'Vardhman Textiles',
      phone: '+91 90080 91234',
      dateTime: at(0, 16, 30),
      action: 'Call about sample dispatch timeline',
    ),
    FollowUp(
      id: 'fu-6',
      leadId: 'lead-5',
      customerName: 'Lakshmi Iyer',
      company: 'KPR Mill',
      phone: '+91 97890 55321',
      dateTime: at(1, 9, 30),
      action: 'Present quotation and payment terms',
      relatedRef: 'QT-430',
    ),
    FollowUp(
      id: 'fu-7',
      leadId: 'lead-6',
      customerName: 'Ashok Menon',
      company: 'Raymond Ltd',
      phone: '+91 98110 77654',
      dateTime: at(2, 15, 0),
      action: 'Negotiate volume discount',
      relatedRef: 'Order #9024',
      outcome: FollowUpOutcome.order,
    ),
    FollowUp(
      id: 'fu-8',
      leadId: 'lead-7',
      customerName: 'Farah Khan',
      company: 'Bombay Dyeing',
      phone: '+91 99870 33221',
      dateTime: at(6, 11, 0),
      action: 'Post-delivery quality check-in',
    ),
  ];
}
