-- AlterEnum MembershipRole
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'PRODUCTION_MANAGER';

-- AlterEnum CallOutcome — canonical Call Status values
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'NOT_REACHABLE';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'CALL_BACK_LATER';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'WHATSAPP_SENT';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'EMAIL_SENT';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'FOLLOW_UP';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_DATE_SET';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'PHYSICAL_MEETING_REQUESTED';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'PHYSICAL_MEETING_PENDING';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'PHYSICAL_MEETING_DONE';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'SAMPLE_REQUESTED';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'SAMPLE_PRODUCTION_IN_PROGRESS';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'SAMPLE_SENT';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_AFTER_SAMPLE';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'DEAL_WON_AFTER_SAMPLE';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'DEAL_WON';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'DEAL_REJECTED_AFTER_SAMPLE';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'DEAL_LOST';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'CLOSED_NOT_NOW';
ALTER TYPE "CallOutcome" ADD VALUE IF NOT EXISTS 'DO_NOT_CONTACT';
