-- AlterEnum: telecaller disposition codes
ALTER TYPE "CallOutcome" ADD VALUE 'CONNECTED_INTERESTED';
ALTER TYPE "CallOutcome" ADD VALUE 'CONNECTED_NOT_INTERESTED';
ALTER TYPE "CallOutcome" ADD VALUE 'RINGING_NO_RESPONSE';
ALTER TYPE "CallOutcome" ADD VALUE 'SWITCHED_OFF';
ALTER TYPE "CallOutcome" ADD VALUE 'ORDER_CONFIRMED';
